#todo docker file esta basado en lago mas, por ejemplo puede ser en una imagen externa
FROM ubuntu:latest
# este comando se corre en tiempo de build, todo lo  que
#decimos en docker file se contruye en teimpo de build
RUN  touch  /usr/src/hola-platzi.txt

RUN rm  /usr/src/hola-platzi.txt